version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "5000:5000"
  ai-engine:
    build: ./ai-engine
    ports:
      - "8000:8000"